version: '3.9'

services:
  test:
    build:
      dockerfile: ./docker/Dockerfile
    container_name: testapp
    restart: always
    working_dir: /app/
    volumes:
      - ./app:/app

  web:
    image: nginx:1.23.3-alpine
    container_name: server
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  db:
    container_name: data
    image: mysql:8.0.31
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"